### ISSUE TITLE
Underwater Layer Clipping

### ISSUE THREAD

**Issue by GeorgeDziov** [huwb/crest-oceanrender#113] opened 2018-11-01 15:03 UTC
https://youtu.be/ncrMMneXGoo

Can't explain the issue, but my guess that somehow underwater mask moves by Z axis forth and back a lil bit, had to raise clipping to 1.35

Not a big issue but thought I'd better post this.

EDIT: Branch - Underwater Skirt, downloaded on 28.10.2018

**Comment by huwb** [comment] 2018-11-01 21:43
I'm not sure. i did fix many bugs on the underwater branch, do you have latest? (its now merged onto master btw)

**Comment by GeorgeDziov** [comment] 2018-11-01 23:29
Ok just tried and it's got better, only some very narrow stripes showing up from time to time but they disappear after setting near to 1.

**Comment by huwb** [comment] 2018-11-02 08:56
Could you send me a screenshot with the inspector visible and the camera selected? I'd like to see:

* Camera fov, near plane, far plane
* Camera transform

Hopefully i can repro it with this.

**Comment by GeorgeDziov** [comment] 2018-11-02 10:20
![camscrshot1](https://user-images.githubusercontent.com/15368122/47909352-b9e92c80-dea0-11e8-9968-899511b43c2d.png)
This is cam with "near" set to 0.01, I set 1.35 to avoid stripes, changing "far" doesn't change anything even if set to 10.

**Comment by huwb** [comment] 2018-11-02 10:43
Oh could i see this while the issue is happening? I.e. a screenshot of the unity window showing the game view and the inspector, with the bug visible.

That near-far range is very extreme, i could imagine 0.01 causing numerical issues. You should push the near plane back as far as possible, something between 0.1 and 1 might work.

But you said you had to push it all the way back to 1.35 which should not be required, so id like to try to investigate further.

**Comment by GeorgeDziov** [comment] 2018-11-02 11:40
https://youtu.be/ubHDJa76Jhs

Changed parameters to demonstrate behavior:

0:00 - 0.01-100 000
0:17 - 0.01-10
0:33 - 1-100 000

**Comment by holdingjason** [comment] 2018-11-02 14:50
Yep seeing this as well.  Any setting below I think 1 on the near clip plane and you see the sides show up.  Easy to repro with latest build.  Was set at 0.1 normally and here is what it looks like.

![image](https://user-images.githubusercontent.com/42001313/47922309-fc484480-de73-11e8-94da-f616a1da8697.png)

**Closed** 2018-11-03 17:55 UTC
Labels: bug

**Comment by huwb** [comment] 2018-11-03 17:56
Issues should be fixed now. There might still be numerical issues with very small clip planes, 0.01 is very small and I recommend using a larger value as i mentioned above.

**Comment by GeorgeDziov** [comment] 2018-11-04 11:43
Works without issues on 0.03, but will be using 0.1 as recommended, respect!
